- name: demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print name
    ansible.builtin.debug:
      msg: "Hello {{ item }}" #item is reseved key word
    loop:
    - Aravind
    - Sivalasetty
    - vscode
